### ISSUE TITLE
Conflict script not creating a new repo

### ISSUE THREAD

**Issue by gusshawstewart** [githubtraining/training-manual#208]
When running the script to create a conflict repo, the repo is not generated for the provider. 
cc @githubtraining/implementation-engineers

**Comment by Glenn-MS** [comment]
Thank you! 
I spent over 3 hours trying to fix this and your workaround "git checkout 3ffc3710" worked perfectly :-)

**Comment by parkerbxyz** [comment]
@Glenn-MS `git checkout 3ffc371` was a workaround from about 2 years ago. The problem was fixed when this issue was closed in May 19, 2020. Using such an old version of the script may cause more problems than it solves for you. I recommend updating to the latest version of the script with `git switch main && git pull`.
