### ISSUE TITLE
Use templates for repo creation

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/training-manual#284]
We should be able to simplify our repo creation in the class scripts and eliminate a potential failure point of having a copy of the class repo locally by taking advantage of repository templates and the new template API.

https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template

**Comment by parkerbxyz** [comment]
I looked into this and found that the template repo must belong to the same organization you want to create the new repo in. So I’m afraid this won’t work unless we change the template locations or the API allows for creating a repo from a template in another organization.

Additionally, since the commit history isn’t included when generating a repo from a template, the only repo this would work for is the `caption-this` repo. The others rely on their history.

**Comment by amyschoen** [comment]
Good call.  I had the thought when templates were new but never circled back to do more research.  We definitely wouldn't want to switch to this approach if it'd mean there wasn't history.
